services:
    singz.paypal.paypal:
        class:     Singz\PaypalBundle\Service\PaypalService
        arguments:
           router: "@router"
           paypal_client_id: "%paypal_client_id%"
           paypal_secret: "%paypal_secret%"