#Admin controller
singz_admin_dashboard:
    path:     /dashboard
    defaults: 
        _controller: SingzAdminBundle:Admin:dashboard
singz_admin_index:
    path:     /
    defaults:
        _controller: SingzAdminBundle:Admin:index
        
#Comment controller
singz_admin_comment_index:
    path:     /comment/
    defaults:
        _controller: SingzAdminBundle:Comment:index
singz_admin_comment_list:
    path:     /comment/list/
    defaults:
        _controller: SingzAdminBundle:Comment:list
singz_admin_comment_show:
    path:     /comment/show/{id}
    defaults:
        _controller: SingzAdminBundle:Comment:show
    requirements:
        id: \d+
        