singz_admin_dashboard:
    path:     /dashboard
    defaults: 
        _controller: SingzAdminBundle:Admin:dashboard

singz_admin_index:
    path:     /
    defaults:
        _controller: SingzAdminBundle:Admin:index



