### ADMIN CONTROLLER ###
singz_admin_admin_routing:
    resource: "@SingzAdminBundle/Resources/config/Admin/routing.yml"
    prefix:   /
  
### COMMENT CONTROLLER ###
singz_admin_comment_routing:
    resource: "@SingzAdminBundle/Resources/config/Comment/routing.yml"
    prefix:   /comment/
        
### USER CONTROLLER ###
singz_admin_user_routing:
    resource: "@SingzAdminBundle/Resources/config/User/routing.yml"
    prefix:   /user/

### SETTINGS CONTROLLER ###
singz_admin_setting_routing:
    resource: "@SingzAdminBundle/Resources/config/Setting/routing.yml"
    prefix:   /setting/
