singz_user_bundle_homepage:
    path:     /{id}/
    defaults:
        _controller: SingzUserBundle:Default:index
    requirements:
        id: \d+

singz_user_enabled:
    path:     /{id}/change-status/{state}
    defaults:
        _controller: SingzUserBundle:User:enabled
    requirements:
        id: \d+
        state: enabled|disabled