singz_user_bundle_homepage:
    path:     /{id}
    defaults:
        _controller: SingzUserBundle:Default:index

singz_social_bundle_follow_user:
    path:    /follow/
    defaults:
        _controller: SingzSocialBundle:User:follow