services:
    singz.user.user:
        class: Singz\UserBundle\EventListener\UserSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    singz.user.edit_my_profile:
        class: Singz\UserBundle\EventListener\EditMyProfileListener
        arguments: ['@router', '@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_subscriber }