singz_social:
    resource: "@SingzSocialBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

singz_core:
    resource: "@SingzCoreBundle/Resources/config/routing.yml"
    prefix:   /