singz_admin:
    resource: "@SingzAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

singz_core:
    resource: "@SingzCoreBundle/Resources/config/routing.yml"
    prefix:   /