singz_admin:
    resource: "@SingzAdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

singz_profile:
    resource: "@SingzUserBundle/Resources/config/routing.yml"
    prefix:   /user/

singz_core:
    resource: "@SingzCoreBundle/Resources/config/routing.yml"
    prefix:   /

singz_social:
    resource: "@SingzSocialBundle/Resources/config/routing.yml"
    prefix:   /

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }