# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        
    role_hierarchy:
        # ROLE_X : ROLE_Y # Cela signifie qu'un utilisateur ayant le ROLE_X a aussi le ROLE_Y
        ROLE_SINGZER:     ROLE_USER
        ROLE_STARZ:       ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username_email
        

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous:    true
            form_login:
                provider: fos_userbundle
                remember_me: true
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
                use_forward: true
                post_only:      true
            logout:       true

    access_control:
        # Tout le monde
        - { path: ^/login$,         role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,       role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        # Besoin d'être connecté et admin pour le back
        - { path: ^/admin,         role: ROLE_ADMIN }
        # Default
        - { path: ^/,               role: IS_AUTHENTICATED_ANONYMOUSLY }