<?php

namespace Singz\CoreBundle\Repository;

/**
 * ContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionRepository extends \Doctrine\ORM\EntityRepository
{
}
