<?php

namespace Singz\CoreBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjectByHashtag($tag){
        return $this->createQueryBuilder('p')
            ->where('REGEXP(p.description, :regexp) = true')
            ->setParameter('regexp', '(#'.$tag.')[^a-zA-Z0-9]')
            ->getQuery()
            ;
    }
}
