<?php

namespace Singz\CoreBundle\Repository;
use Singz\CoreBundle\Entity\Project;
/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjectByHashtag($hashtag){
        return $this->createQueryBuilder('p')
            ->where('REGEXP(p.description, :regexp) = true')->setParameter('regexp', '#'.$hashtag.'\b')
            ->andWhere('p.state = :state')
            ->setParameter('state', Project::STATE_VISIBLE)
            ->orderBy('p.amountReached', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
