<?php

namespace Singz\CoreBundle\Repository;
use Singz\CoreBundle\Entity\Project;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProjectByHashtag($hashtag){
        return $this->createQueryBuilder('p')
            ->where('REGEXP(p.description, :regexp) = true')->setParameter('regexp', '#'.$hashtag.'\b')
            ->andWhere('p.state = :state')
            ->setParameter('state', Project::STATE_VISIBLE)
            ->orderBy('p.amountReached', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }

    public function findBySearchTerm($search){
        return $this->createQueryBuilder('p')
            ->where('REGEXP(p.name, :regexp) = true')->setParameter('regexp', $search)
            ->orWhere('REGEXP(p.description, :regexp) = true')->setParameter('regexp', $search)
            ->andWhere('p.state = :state')
            ->setParameter('state', Project::STATE_VISIBLE)
            ->orderBy('p.amountReached', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }

	public function getProject($id){
		return $this->createQueryBuilder('p')
			// contributions
			->leftJoin('p.contributions', 'c', 'WITH', 'c.isValidated = :contributionValidated')
				->addSelect('c')
				->setParameter('contributionValidated', true)
			// id project
			->andWhere('p.id = :id')
				->setParameter('id', $id)
		
			->getQuery()
			->getOneOrNullResult()
		;
	}

    public function findAllProjectsInfo(){
        return $this->createQueryBuilder('p')
            ->leftJoin('p.requester', 'r')->addSelect('r')
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
