<?php

namespace Singz\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUsersList() {
		return $this->createQueryBuilder('u')
		->innerJoin('u.image', 'i')->addSelect('i')
		->orderBy('u.username', 'ASC')
		->getQuery()
		->getResult();
	}
}
