<?php

namespace Singz\UserBundle\Repository;


use Singz\SocialBundle\Entity\Publication;
use Singz\CoreBundle\Entity\Project;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUsersList() {
		return $this->createQueryBuilder('u')
		->leftJoin('u.image', 'i')->addSelect('i')
		->orderBy('u.username', 'ASC')
		->getQuery()
		->getResult();
	}
	
	public function getUser($username, $enabled = true){
		return $this->createQueryBuilder('u')
			// image
			->leftJoin('u.image', 'image')
				->addSelect('image')			
			// publications
			->leftJoin('u.publications', 'publications', 'WITH', 'publications.state = :publicationState')
				->addSelect('publications')
				->setParameter('publicationState', Publication::STATE_VISIBLE)
			->leftJoin('publications.video', 'video')
				->addSelect('video')
			// projects
			->leftJoin('u.projects', 'projects', 'WITH', 'projects.state = :projectState')
				->addSelect('projects')
				->setParameter('projectState', Project::STATE_VISIBLE)
			// contributions
			->leftJoin('u.contributions', 'contributions', 'WITH', 'contributions.isValidated = :isValidated')
				->addSelect('contributions')
				->setParameter('isValidated', true)
			// check state
			->andWhere('u.enabled = :enabled')
				->setParameter('enabled', $enabled)
			// username
			->andWhere('u.username = :username')
				->setParameter('username', $username)
				
			->getQuery()
			->getOneOrNullResult()
		;
	}
    public function findBySearchTerm($search){
        return $this->createQueryBuilder('u')
            ->where('REGEXP(u.username, :regexp) = true')->setParameter('regexp', $search)
            ->orWhere('REGEXP(u.biography, :regexp) = true')->setParameter('regexp', $search)
            ->andWhere('u.enabled = :enabled')
            ->setParameter('enabled', true)
            ->getQuery()
            ->getResult()
            ;
    }

}
