<?php

namespace Singz\SocialBundle\Repository;

/**
 * FollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRealFollows($user){
        return $this->createQueryBuilder('f')
            ->where('f.leader = :leader AND f.isPending = :pending')
            ->setParameter('leader', $user)
            ->setParameter('pending', false)
            ->getQuery()
            ->getResult();
    }

    public function getRealLeads($user){
        return $this->createQueryBuilder('f')
            ->where('f.follower = :follower AND f.isPending = :pending')
            ->setParameter('follower', $user)
            ->setParameter('pending', false)
            ->getQuery()
            ->getResult();
    }
}
