<?php

namespace Singz\SocialBundle\Repository;

/**
 * LoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoveRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastWeekLoves($lastweek){
        return $this->createQueryBuilder('l')
            ->where('l.date > :lastweek')
            ->setParameter('lastweek', $lastweek)
            ->getQuery()
            ->getResult()
        ;
    }

    public function getLovers($publication){
        return $this->createQueryBuilder('l')
            ->where('l.publication = :publication')
            ->setParameter('publication', $publication)
            ->getQuery()
            ->getResult()
        ;
    }
}
