<?php

namespace Singz\SocialBundle\Repository;

use Singz\UserBundle\Entity\User;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNotificationsByUser(User $user){
		return $this->createQueryBuilder('n')
			->innerJoin('n.user', 'notification_user')->addSelect('notification_user')
			->innerJoin('notification_user.image', 'i')->addSelect('i')
			->innerJoin('n.publication', 'p')->addSelect('p')
			->innerJoin('p.user', 'publication_user')->addSelect('publication_user')
			->andWhere('publication_user.id = :user_id')
			->setParameter('user_id', $user->getId())
			->orderBy('n.date', 'DESC')
			->getQuery()
			->getResult();
	}
}
