singz_admin_comment_index:
    path:     /
    defaults:
        _controller: SingzAdminBundle:Comment:index
singz_admin_comment_list:
    path:     /list/
    defaults:
        _controller: SingzAdminBundle:Comment:list