### PUBLICATION CONTROLLER ###
singz_social_publication_routing:
    resource: "@SingzSocialBundle/Resources/config/Publication/routing.yml"
    prefix:   /publication/

### NOTIFICATION CONTROLLER ###
singz_social_notification_routing:
    resource: "@SingzSocialBundle/Resources/config/Notification/routing.yml"
    prefix:   /notification/