
singz_social_bundle_publication_index:
    path:     /publication/
    defaults: { _controller: SingzSocialBundle:Publication:index }

singz_social_bundle_publication_new:
    path:     /publication/new/
    defaults: { _controller: SingzSocialBundle:Publication:new }

singz_social_bundle_publication_list:
    path:     /publication/list/
    defaults: { _controller: SingzSocialBundle:Publication:list }

singz_social_bundle_publication_show:
    path:     /publication/{id}
    defaults: { _controller: SingzSocialBundle:Publication:show }
    requirements:
        id: \d+

singz_social_bundle_publication_love:
    path:     /publication/love/
    defaults: { _controller: SingzSocialBundle:Publication:love }
