singz_social_bundle_publication_index:
    path:     /publication/
    defaults:
        _controller: SingzSocialBundle:Publication:index

singz_social_bundle_publication_show:
    path:     /publication/{id}
    defaults:
        _controller: SingzSocialBundle:Publication:show
    requirements:
        id: \d+

singz_social_bundle_publication_edit:
    path:     /publication/{id}/edit
    defaults:
        _controller: SingzSocialBundle:Publication:edit
    requirements:
        id: \d+

singz_social_bundle_publication_new:
    path:     /publication/new/
    defaults:
        _controller: SingzSocialBundle:Publication:new

# ajax
singz_social_bundle_publication_love:
    path:     /publication/love/
    defaults:
        _controller: SingzSocialBundle:Publication:love

# ajax
singz_social_bundle_publication_extra_info:
    path:     /publication/extra/
    defaults:
        _controller: SingzSocialBundle:Publication:getPublicationExtra
        