services:
    singz.social.publication:
        class: Singz\SocialBundle\EventListener\PublicationSubscriber
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    singz.social.love:
        class: Singz\SocialBundle\EventListener\LoveSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    singz.social.comment:
        class: Singz\SocialBundle\EventListener\CommentSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    singz.social.follow:
        class: Singz\SocialBundle\EventListener\FollowSubscriber
        arguments: ["@service_container"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    singz.social.report:
        class: Singz\SocialBundle\EventListener\ReportSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }