services:
    singz.social.publication:
        class: Singz\SocialBundle\EventListener\PublicationSubscriber
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_subscriber, connection: default }