services:
    singz.social.publication:
        class: Singz\SocialBundle\EventListener\PublicationSubscriber
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    singz.social.love:
        class: Singz\SocialBundle\EventListener\LoveSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    singz.social.comment:
        class: Singz\SocialBundle\EventListener\CommentSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    singz.social.follow:
        class: Singz\SocialBundle\EventListener\FollowSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }