services:
    singz.doctrine.upload:
        class: Singz\VideoBundle\DoctrineListener\VideoUpload
        arguments:
            - "@dubture_ffmpeg.ffprobe"
        tags:
            - { name: doctrine.event_listener, event: prePersist }