services:
    singz.doctrine.upload:
        class: Singz\VideoBundle\EventListener\VideoUploadSubscriber
        arguments:
            - "@dubture_ffmpeg.ffprobe"
            - "@dubture_ffmpeg.ffmpeg"
        tags:
            - { name: doctrine.event_subscriber, connection: default }