services:
    singz.video.video:
        class: Singz\VideoBundle\EventListener\VideoSubscriber
        arguments:
            - "@dubture_ffmpeg.ffprobe"
            - "@dubture_ffmpeg.ffmpeg"
        tags:
            - { name: doctrine.event_subscriber, connection: default }