singz_core_bundle_project_new:
    path:     /new/
    defaults:
        _controller: SingzCoreBundle:Project:new

singz_core_bundle_project_show:
    path:     /{id}/show/
    defaults:
        _controller: SingzCoreBundle:Project:show
    requirements:
        id: \d+

singz_core_bundle_project_edit:
    path:     /{id}/edit/
    defaults:
        _controller: SingzCoreBundle:Project:edit
    requirements:
        id: \d+

singz_core_bundle_project_delete:
    path:     /{id}/delete/
    defaults:
        _controller: SingzCoreBundle:Project:delete
    requirements:
        id: \d+
        
singz_core_bundle_project_contributing:
    path:     /{id}/contributing/
    defaults:
        _controller: SingzCoreBundle:Project:contributing
    requirements:
        id: \d+