singz_core_bundle_project_new:
    path:     /new/
    defaults:
        _controller: SingzCoreBundle:Project:new

singz_core_bundle_project_show:
    path:     /{id}/show/
    defaults:
        _controller: SingzCoreBundle:Project:show
    requirements:
        id: \d+