### PROJECT CONTROLLER ###
singz_core_core_routing:
    resource: "@SingzCoreBundle/Resources/config/Core/routing.yml"
    prefix:   /

### PROJECT CONTROLLER ###
singz_core_project_routing:
    resource: "@SingzCoreBundle/Resources/config/Project/routing.yml"
    prefix:   /project/