singz_index:
    path:     /
    defaults:
        _controller: SingzCoreBundle:Core:index

singz_browse:
    path: /browse/{filter}/
    requirements:
        filter: '(all|singzer|starz)'
    defaults:
        _controller: SingzCoreBundle:Core:browse

singz_browse_all:
    path: /browse/
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /browse/all/
        permanent: true