services:
    singz.core.project:
        class: Singz\CoreBundle\EventListener\ProjectSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    singz.core.contribution:
        class: Singz\CoreBundle\EventListener\ContributionSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }